### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by SteveZuercher** [mrgnth/PyPDF-Builder#5]
2 things:

1. I was unable to install with the requirements.txt. MarkupSafe was erroring when I tried to install v1.0, so I had to use v1.1.1. I'm on Python 3.8. pip install worked fine after that.

2. I am unable to run the pyinstaller. here's my output window. Any ideas?

```
pyinstaller --onefile --clean --windowed --add-data="mainwindow.ui:." --hidden-import="pygubu.builder.ttkstdwidgets" --hidden-import="pygubu.builder.widgets.dialog" pypdfbuilder.py
usage: pyinstaller [-h] [-v] [-D] [-F] [--specpath DIR] [-n NAME] [--add-data <SRC;DEST or SRC:DEST>]
                   [--add-binary <SRC;DEST or SRC:DEST>] [-p DIR] [--hidden-import MODULENAME]
                   [--additional-hooks-dir HOOKSPATH] [--runtime-hook RUNTIME_HOOKS] [--exclude-module EXCLUDES]
                   [--key KEY] [-d] [-s] [--noupx] [-c] [-w] [-i <FILE.ico or FILE.exe,ID or FILE.icns>]
                   [--version-file FILE] [-m <FILE or XML>] [-r RESOURCE] [--uac-admin] [--uac-uiaccess]
                   [--win-private-assemblies] [--win-no-prefer-redirects] [--osx-bundle-identifier BUNDLE_IDENTIFIER]
                   [--runtime-tmpdir PATH] [--distpath DIR] [--workpath WORKPATH] [-y] [--upx-dir UPX_DIR] [-a]
                   [--clean] [--log-level LEVEL]
                   scriptname [scriptname ...]
pyinstaller: error: argument --add-data: invalid add_data_or_binary value: 'mainwindow.ui:.'
```

**Comment by teschmitt** [comment]
Hi Steve, I haven't touched this in a long time but I'll try to figure out what's going wrong in the coming days. It might be something as simple as the Python version you're using … what OS are you running on?
edit: I just saw I have to upgrade a lot of dependencies anyway, so maybe that will straighten things out.

**Comment by SteveZuercher** [comment]
I'm running on windows 10, build 19041.804. I forgot to mention that my version of python is the 64 bit variant. not sure if that matters or not. Thanks for taking time to look into this!

**Comment by teschmitt** [comment]
Hi Steve, @DeepBlueBW managed to follow up on this issue and it seems to be solved by using a slightly different format in the command line options on Windows. As I'm running Linux I wasn't aware of this:
```sh
pyinstaller --onefile --clean --windowed --add-data="mainwindow.ui;." \
    --hidden-import="pygubu.builder.ttkstdwidgets" \
    --hidden-import="pygubu.builder.widgets.dialog" \
    pypdfbuilder.py
```
The difference is in the `--add-data` argument, where Windows needs a semi-colon, Linux needs a colon. If you use the above command everything should work fine.

Thanks for bringing this up, @DeepBlueBW has already updated the README accordingly.

Please let us know if this solves the issue for you and we can close it.

**Comment by teschmitt** [comment]
I assume this is solved and I'll close the issue. Please feel free to reopen if issues persist.
